import { useState } from 'react';
import { AppButton, AppSelect, Card, InputGroup } from '../../components/base';
import { X } from '../../ui/icons';

export type MeasurementModalValues = { tglUkur: string; bb: string; tb: string; lila: string; lk: string; caraUkur: string; edema: string; kelasIbu: string; mbg: string; vitA: string; asi: string };
export type MeasurementModalProps = { child: Record<string, any>; initialValues?: Partial<MeasurementModalValues>; onClose: () => void; onSubmit: (values: MeasurementModalValues) => Promise<void> | void; };
const options = (values: string[]) => values.map((value) => ({ value, label: value }));
const control = 'w-full rounded-xl border border-slate-200 bg-slate-50 p-2.5 text-sm focus:border-emerald-500 focus:ring-emerald-100';

/** Reusable React measurement dialog; persistence remains owned by the page/write service. */
export default function MeasurementModal({ child, initialValues, onClose, onSubmit }: MeasurementModalProps) {
  const [values, setValues] = useState<MeasurementModalValues>({ tglUkur: '', bb: '', tb: '', lila: '', lk: '', caraUkur: 'Terlentang', edema: 'Tidak', kelasIbu: 'Tidak', mbg: 'Tidak', vitA: 'Tidak', asi: 'Tidak', ...initialValues });
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (key: keyof MeasurementModalValues, value: string) => setValues((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setSaving(true); setError(null); try { await onSubmit(values); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Data pengukuran gagal disimpan.'); } finally { setSaving(false); } };
  const field = (key: keyof MeasurementModalValues, label: string, type = 'text') => <InputGroup label={label}><input required={['tglUkur', 'bb', 'tb', 'lk'].includes(key)} type={type} inputMode={type === 'date' ? undefined : 'decimal'} className={control} value={values[key]} onChange={(event) => update(key, event.target.value)} /></InputGroup>;
  const select = (key: keyof MeasurementModalValues, label: string, valuesList: string[]) => <InputGroup label={label}><AppSelect value={values[key]} options={options(valuesList)} onChange={(event) => update(key, event.target.value)} /></InputGroup>;
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-900/50 p-4 backdrop-blur-md" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><Card className="w-full max-w-3xl overflow-hidden" role="dialog" aria-modal="true" aria-labelledby="react-measurement-modal-title"><header className="flex items-start justify-between border-b border-slate-200 p-5"><div><h2 id="react-measurement-modal-title" className="text-lg font-bold">Pengukuran Balita</h2><p className="text-sm text-slate-500">{String(child.nama || 'Balita')}</p></div><button type="button" onClick={onClose} aria-label="Tutup"><X /></button></header><form onSubmit={submit} className="grid gap-4 p-5 sm:grid-cols-2">{field('tglUkur', 'Tanggal Pengukuran', 'date')}{select('caraUkur', 'Cara Ukur', ['Terlentang', 'Berdiri'])}{field('bb', 'Berat Badan (kg)')}{field('tb', 'Panjang/Tinggi Badan (cm)')}{field('lila', 'LILA (cm)')}{field('lk', 'Lingkar Kepala (cm)')}{select('edema', 'Pitting Edema Bilateral', ['Tidak', 'Ada (Derajat +1)', 'Ada (Derajat +2)', 'Ada (Derajat +3)'])}{select('kelasIbu', 'Kelas Ibu Balita?', ['Tidak', 'Ya'])}<InputGroup label="Terima MBG?"><AppSelect value={values.mbg} options={options(['Tidak', 'Ya'])} onChange={(event) => update('mbg', event.target.value)} /><p className="text-[11px] italic text-slate-500">*Balita yang menerima PMT dari Posyandu atau PAUD/TK.</p></InputGroup>{select('vitA', 'Dapat Vitamin A (Feb/Agu)?', ['Tidak', 'Ya'])}{select('asi', 'ASI Eksklusif (umur balita)', ['Tidak', 'Ya'])}{error ? <p className="sm:col-span-2 rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700" role="alert">{error}</p> : null}<div className="flex justify-end gap-3 border-t border-slate-200 pt-4 sm:col-span-2"><AppButton type="button" variant="secondary" onClick={onClose}>Batal</AppButton><AppButton type="submit" disabled={saving}>{saving ? 'Menyimpan…' : 'Simpan Pengukuran'}</AppButton></div></form></Card></div>;
}
