[package]
name = "e-posyandu-cloudflare-worker"
version = "4.4.5"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
base64 = "0.22"
graphql-parser = "0.4"
hex = "0.4"
hmac = "0.12"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
sha2 = "0.10"
url = "2"
worker = { version = "0.8.5", features = ["queue"] }

[profile.release]
lto = true
opt-level = "s"
strip = true
codegen-units = 1
