import { useState } from 'react';
import { addDoc, collection, serverTimestamp, syncPendingMutations } from '../../api/syncApi';
import { appId, db } from '../../app/session';
import { formatDate, normalizeDecimalInput, parseLocaleNumber } from '../../shared/formatters';
import { errorMessage } from '../../shared/pageState';
import { AppButton, AppSelect, Card, InputGroup } from '../../components/base';
import { Gift, X } from '../../ui/icons';
import { showSuccess } from '../../ui/notifications';

type Child = Record<string, any>;
export type PmtModalProps = { child: Child; category: string; onClose: () => void; onSaved?: () => void };
const select = (values: string[]) => values.map((value) => ({ value, label: value }));
const control = 'ios-liquid-control w-full rounded-xl p-2.5';

export default function PmtModal({ child, category, onClose, onSaved }: PmtModalProps) {
  const [form, setForm] = useState({ jenisPmt: 'Pabrikan', sumberAnggaran: 'Dana Desa', mitra: '', mitraLain: '', tglPemberian: formatDate(new Date()), siklusKe: '1', pmtSesuaiJuknis: 'Ya' });
  const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const update = (key: keyof typeof form, value: string) => setForm((current) => ({ ...current, [key]: value }));
  const submit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault(); const siklus = parseLocaleNumber(form.siklusKe); if (siklus === null || !Number.isFinite(siklus) || siklus <= 0) { setError('Siklus PMT wajib diisi angka desimal yang valid.'); return; }
    setSaving(true); setError(null);
    try { await addDoc(collection(db, 'artifacts', appId, 'public', 'data', 'pmt_programs'), { childId: child.id, childName: child.nama, category, jenisPmt: form.jenisPmt, sumberAnggaran: form.sumberAnggaran, mitra: form.mitra, mitraLain: form.mitraLain, tglPemberian: form.tglPemberian, siklusKe: siklus, pmtSesuaiJuknis: form.pmtSesuaiJuknis, status: 'Aktif', initialMeasurementDate: child.lastMeasurementDate || form.tglPemberian, initialBB: child.currentBB || child.bbLahir || null, initialTB: child.currentTB || child.pbLahir || null, monitorings: {}, createdAt: serverTimestamp() }); await syncPendingMutations(); showSuccess('Program PMT berhasil ditambahkan.'); onSaved?.(); onClose(); } catch (cause) { setError(errorMessage(cause, 'Program PMT gagal disimpan.')); } finally { setSaving(false); }
  };
  return <div className="ios-modal-backdrop fixed inset-0 z-50 flex items-center justify-center p-4" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><Card className="ios-liquid-modal ios-pmt-create-modal max-h-[90vh] w-full max-w-2xl overflow-y-auto" role="dialog" aria-modal="true" aria-labelledby="react-pmt-create-title"><header className="ios-modal-header flex items-start justify-between"><div className="flex items-center gap-3"><span className="apple-symbol-tile apple-symbol-tile-green"><Gift /></span><div><h2 id="react-pmt-create-title" className="text-lg font-bold">Pemberian PMT</h2><p className="text-sm text-slate-500">{String(child.nama || 'Balita')}</p></div></div><button type="button" onClick={onClose} className="ios-modal-close" aria-label="Tutup pemberian PMT"><X /></button></header><form onSubmit={submit} className="ios-modal-body space-y-4"><div className="ios-modal-context"><span>Kategori intervensi</span><strong>{category}</strong></div><div className="grid gap-4 sm:grid-cols-2"><InputGroup label="Siklus Ke-"><input required inputMode="decimal" className={control} value={form.siklusKe} onChange={(event) => update('siklusKe', normalizeDecimalInput(event.target.value))} /></InputGroup><InputGroup label="Jenis PMT"><AppSelect value={form.jenisPmt} options={select(['Pabrikan', 'Lokal'])} onChange={(event) => update('jenisPmt', event.target.value)} /></InputGroup><InputGroup label="Sumber Anggaran"><AppSelect value={form.sumberAnggaran} options={select(['Dana Desa', 'DAK Non Fisik', 'APBD', 'Mitra'])} onChange={(event) => update('sumberAnggaran', event.target.value)} /></InputGroup>{form.sumberAnggaran === 'Mitra' ? <InputGroup label="Nama Mitra"><input className={control} value={form.mitra} onChange={(event) => update('mitra', event.target.value)} /></InputGroup> : null}{form.sumberAnggaran === 'Mitra' && form.mitra === 'Lainnya' ? <InputGroup label="Mitra Lainnya"><input className={control} value={form.mitraLain} onChange={(event) => update('mitraLain', event.target.value)} /></InputGroup> : null}<InputGroup label="PMT Sesuai Juknis?"><AppSelect value={form.pmtSesuaiJuknis} options={select(['Ya', 'Tidak'])} onChange={(event) => update('pmtSesuaiJuknis', event.target.value)} /></InputGroup><InputGroup label="Tanggal Mulai Pemberian"><input required type="date" className={control} value={form.tglPemberian} onChange={(event) => update('tglPemberian', event.target.value)} /></InputGroup></div>{error ? <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<div className="ios-modal-actions flex gap-3"><AppButton type="button" variant="secondary" onClick={onClose} className="flex-1">Batal</AppButton><AppButton type="submit" disabled={saving} className="flex-1">{saving ? 'Menyimpan…' : 'Simpan Program'}</AppButton></div></form></Card></div>;
}
