import { useState } from 'react';
import { AppButton, AppSelect, Card, InputGroup } from '../../components/base';
import { AlertTriangle, X } from '../../ui/icons';
import { errorMessage } from '../../shared/pageState';

type Child = Record<string, any>;
export type DeleteChildModalProps = { child: Child; onClose: () => void; onConfirm: (id: string, payload: Record<string, string>) => Promise<void> | void };
const reasons = [{ value: 'Salah Input', label: 'Salah Input / Langsung Hapus' }, { value: 'Pindah Domisili', label: 'Pindah Domisili' }, { value: 'Meninggal Dunia', label: 'Meninggal Dunia' }];
const inputClass = 'w-full rounded-xl border border-slate-200 bg-slate-50 p-2.5 text-sm focus:border-rose-500 focus:ring-rose-100';

export default function DeleteChildModal({ child, onClose, onConfirm }: DeleteChildModalProps) {
  const [reason, setReason] = useState('Salah Input'); const [deathDate, setDeathDate] = useState(''); const [deathCause, setDeathCause] = useState(''); const [deathLocation, setDeathLocation] = useState(''); const [saving, setSaving] = useState(false); const [error, setError] = useState<string | null>(null);
  const submit = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!child.id) { setError('Data balita tidak ditemukan.'); return; } setSaving(true); setError(null); try { await onConfirm(String(child.id), { deleteReason: reason, ...(reason === 'Meninggal Dunia' ? { deathDate, deathCause, deathLocation } : {}) }); onClose(); } catch (cause) { setError(errorMessage(cause, 'Data balita gagal dihapus.')); } finally { setSaving(false); } };
  return <div className="fixed inset-0 z-50 flex items-center justify-center overflow-y-auto bg-slate-900/50 p-4 backdrop-blur-sm" role="presentation" onMouseDown={(event) => { if (event.target === event.currentTarget && !saving) onClose(); }}><Card className="w-full max-w-md overflow-hidden" role="dialog" aria-modal="true" aria-labelledby="react-delete-child-title"><header className="flex items-start gap-3 border-b border-rose-100 bg-rose-50 p-5"><span className="rounded-full bg-rose-100 p-2 text-rose-600"><AlertTriangle /></span><div className="flex-1"><h2 id="react-delete-child-title" className="font-bold text-rose-700">Hapus Data Balita</h2><p className="mt-1 text-sm text-rose-600">Data akan dipindahkan ke Recycle Bin.</p></div><button type="button" onClick={onClose} aria-label="Tutup"><X /></button></header><form onSubmit={submit} className="space-y-4 p-5"><div className="rounded-xl border border-slate-100 bg-slate-50 p-3"><p className="font-semibold text-slate-700">{String(child.nama || 'Balita')}</p><p className="mt-1 font-mono text-xs text-slate-500">{String(child.nik || '-')}</p></div><InputGroup label="Alasan Menghapus"><AppSelect value={reason} options={reasons} onChange={(event) => setReason(event.target.value)} /></InputGroup>{reason === 'Meninggal Dunia' ? <div className="space-y-3 rounded-xl border border-rose-100 bg-rose-50 p-3"><p className="text-xs text-rose-600">Lengkapi data kematian untuk pelaporan.</p><InputGroup label="Tanggal Meninggal"><input required type="date" className={inputClass} value={deathDate} onChange={(event) => setDeathDate(event.target.value)} /></InputGroup><InputGroup label="Penyebab Meninggal"><input required className={inputClass} value={deathCause} onChange={(event) => setDeathCause(event.target.value)} /></InputGroup><InputGroup label="Lokasi Meninggal"><input required className={inputClass} value={deathLocation} onChange={(event) => setDeathLocation(event.target.value)} /></InputGroup></div> : null}{error ? <p role="alert" className="rounded-xl border border-rose-200 bg-rose-50 p-3 text-sm text-rose-700">{error}</p> : null}<div className="flex gap-3 pt-2"><AppButton type="button" variant="secondary" onClick={onClose} className="flex-1">Batal</AppButton><AppButton type="submit" variant="dangerFilled" disabled={saving} className="flex-1">{saving ? 'Menghapus…' : 'Hapus Data'}</AppButton></div></form></Card></div>;
}
