begin;

-- The child table exposes two NIK sources: a manually entered civil NIK
-- (has_national_id = true) and a temporary NIK generated by the application
-- (has_national_id = false).  Keep this predicate in PostgreSQL so filtering
-- happens before server pagination and the reported total remains exact.
create or replace function public.eposyandu_nik_filter_match(
  p_has_nik boolean,
  p_search text
) returns boolean
language sql
immutable
as $$
  select case
    when left(coalesce(p_search, ''), 6) = '__N0__' then not coalesce(p_has_nik, false)
    when left(coalesce(p_search, ''), 6) = '__N1__' then coalesce(p_has_nik, false)
    else true
  end
$$;

-- Search text is transported through the existing p_search argument to keep
-- all deployed RPC signatures backward-compatible during a rolling update.
-- The marker is removed before name/NIK matching, so a NIK filter and a text
-- search can be used together.
create or replace function public.eposyandu_child_search_term(
  p_search text
) returns text
language sql
immutable
as $$
  select case
    when left(coalesce(p_search, ''), 6) in ('__N0__', '__N1__')
      then nullif(substr(p_search, 7), '')
    else p_search
  end
$$;

do $$
declare
  function_definition text;
  corrected_definition text;
  function_name text;
  function_arguments text;
begin
  foreach function_name in array array[
    'eposyandu_replica_children_page',
    'eposyandu_materialized_children_page'
  ] loop
    function_arguments := case function_name
      when 'eposyandu_replica_children_page' then
        'p_as_of date, p_measurement_start date, p_measurement_end date, p_page integer, p_size integer, p_sort text, p_view text, p_search text, p_village text, p_posyandu text, p_role text, p_scope_village text, p_scope_posyandu text, p_age_group text'
      else
        'p_as_of date, p_measurement_start date, p_measurement_end date, p_page integer, p_size integer, p_sort text, p_view text, p_search text, p_village text, p_posyandu text, p_role text, p_scope_village text, p_scope_posyandu text, p_age_group text'
    end;

    select pg_get_functiondef(p.oid)
      into function_definition
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public'
      and p.proname = function_name
      and pg_get_function_identity_arguments(p.oid) = function_arguments;

    if function_definition is null then
      raise exception '% with signature % is not installed', function_name, function_arguments;
    end if;

    -- Both age-aware page functions contain this same search predicate. Add
    -- the NIK source predicate beside it, then strip the private marker from
    -- the text search expression itself.
    corrected_definition := replace(
      function_definition,
      'and (nullif(trim(coalesce(p_search, '''')), '''') is null',
      'and public.eposyandu_nik_filter_match(c.has_national_id, p_search)' || chr(10) ||
      '      and (nullif(trim(coalesce(public.eposyandu_child_search_term(p_search), '''')), '''') is null'
    );
    corrected_definition := replace(
      corrected_definition,
      'trim(p_search) ||',
      'trim(public.eposyandu_child_search_term(p_search)) ||'
    );

    if corrected_definition = function_definition then
      -- Idempotent when a deployment is retried after the function was
      -- already corrected by an interrupted migration run.
      continue;
    end if;
    execute corrected_definition;
  end loop;
end
$$;

revoke all on function public.eposyandu_nik_filter_match(boolean, text) from public;
revoke all on function public.eposyandu_child_search_term(text) from public;
do $$
begin
  if exists (select 1 from pg_roles where rolname = 'service_role') then
    execute 'grant execute on function public.eposyandu_nik_filter_match(boolean,text) to service_role';
    execute 'grant execute on function public.eposyandu_child_search_term(text) to service_role';
  end if;
  if exists (select 1 from pg_roles where rolname = 'eposyandu_api') then
    execute 'grant execute on function public.eposyandu_nik_filter_match(boolean,text) to eposyandu_api';
    execute 'grant execute on function public.eposyandu_child_search_term(text) to eposyandu_api';
  end if;
end
$$;

insert into public.schema_migrations(version, description)
values ('053', 'filter child registry by manual or generated NIK source')
on conflict (version) do nothing;

commit;
