[package]
name = "e-posyandu-operations-service"
version = "3.7.0"
edition = "2024"
publish = false

[dependencies]
e-posyandu-oracle-domain = { path = "../oracle-domain" }
e-posyandu-proto = { path = "../eposyandu-proto" }
tokio = { version = "1", features = ["macros", "net", "rt-multi-thread", "signal"] }
tokio-stream = { version = "0.1", features = ["net"] }
tonic = { version = "0.14", features = ["transport"] }
tonic-health = "0.14"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "json"] }
