import { useRef, useState } from 'react';
import { completeAdminInvitation, type SignInResult } from '../../api/authApi';
import { AppButton, Card, InputGroup } from '../../components/base';

export type ReactAdminInvitePageProps = { accessToken: string; refreshToken: string; onComplete: (result: SignInResult) => Promise<void>; onCancel: () => Promise<void> };

export default function ReactAdminInvitePage({ accessToken, refreshToken, onComplete, onCancel }: ReactAdminInvitePageProps) {
  const [password, setPassword] = useState(''); const [confirmation, setConfirmation] = useState(''); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false); const passwordRef = useRef<HTMLInputElement | null>(null);
  const submit = async (event: React.FormEvent) => { event.preventDefault(); setError(null); if (password !== confirmation) { setError('Konfirmasi kata sandi tidak sama.'); return; } if (password.length < 14) { setError('Kata sandi minimal 14 karakter.'); return; } setSaving(true); try { const result = await completeAdminInvitation(accessToken, refreshToken, password); setPassword(''); setConfirmation(''); await onComplete(result); } catch (cause) { setError(cause instanceof Error ? cause.message : 'Undangan tidak dapat diaktifkan.'); } finally { setSaving(false); } };
  return <div className="login-shell"><div className="login-batik-background" aria-hidden="true" /><main className="login-stage"><div className="login-stack"><Card className="login-glass-card p-6 sm:p-8"><div className="login-brand"><div className="login-logo-shell"><img src="/logo-puskesmas-32981.svg" alt="Logo Puskesmas Gumukmas" className="h-11 w-11 object-contain" width={44} height={44} loading="eager" decoding="async" /></div><h1 className="login-title">Aktivasi Akun</h1><p className="login-organization">E-Posyandu Puskesmas Gumukmas</p></div><form onSubmit={submit} className="login-form mt-6 space-y-4"><p className="text-sm text-slate-600">Buat kata sandi unik untuk akun E-Posyandu Anda. Administrator akan melanjutkan ke verifikasi dua langkah.</p><InputGroup label="Kata sandi baru"><input ref={passwordRef} autoFocus required minLength={14} type="password" autoComplete="new-password" value={password} onChange={(event) => setPassword(event.target.value)} className="login-input" /></InputGroup><InputGroup label="Ulangi kata sandi"><input required minLength={14} type="password" autoComplete="new-password" value={confirmation} onChange={(event) => setConfirmation(event.target.value)} className="login-input" /></InputGroup><p className="text-xs text-slate-500">Minimal 14 karakter dengan huruf besar, huruf kecil, angka, dan simbol.</p>{error ? <p role="alert" className="login-error">{error}</p> : null}<AppButton type="submit" disabled={saving} className="w-full">{saving ? 'Menyimpan…' : 'Aktifkan akun'}</AppButton><AppButton type="button" variant="secondary" disabled={saving} onClick={() => void onCancel()} className="w-full">Batalkan</AppButton></form></Card></div></main><footer className="login-footer"><p>E-Posyandu v3.8.1</p></footer></div>;
}
